name: Format

on: [push, pull_request]

jobs:
  python-format:
    name: 'Python Format'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - uses: astral-sh/setup-uv@v5

    - name: Install python libraries
      shell: bash
      run: |
        uv sync --locked --group test

    - name: Run black
      shell: bash
      run: uv run black --check .

    - name: Run pylint
      shell: bash
      run: uv run pylint reccmp tests

    - name: Run mypy
      shell: bash
      run: uv run mypy ./reccmp ./tests

  js-format:
    name: 'Javascript Format'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      working-directory: ./webui
      run: |
        npm ci

    - name: Biome Format (tests)
      working-directory: ./webui
      run: |
        npm run lint
